name: Post Now Playing to Bluesky

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required tools
        run: pip install requests atproto pylast


      - name: Run script
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
        run: python nowplaying.py
